### PR TITLE
Style form page

### PR DESCRIPTION
**Pull request by theodorosploumis**
Just a better styling for the form page. 
Also, I think that the official form link should be added on the project "About" sidebar on GitHub.

<a href="https://gitpod.io/#https://github.com/drud/ddev-gitpod-launcher/pull/8"></a>

### CODE REVIEW

**Comment by rfay** [comment]
Awesome! I was waiting for you to get here!

I improved the "About" description.

**Comment by rfay** [comment]
To make this easy to test, you need to set up github pages to use the `docs` directory on the branch you used (main)

**Comment by theodorosploumis** [comment]
I thought initially that the link was from a company domain. My mistake :-)

**Review by rfay — APPROVED** [review]
Looking beautiful, thanks!

**Pull request merged**
