### PR TITLE
Replace underscore with slash for reponame so ddev config --auto does…

### PR DESCRIPTION
**Pull request by theodorosploumis**
Some git repositories may contain an underscore `_`. This makes command `ddev config --auto` fail because underscore is not allowed for host names.

You can see this issue for example if you try to open repository https://github.com/goalgorilla/open_social.

As a quick fix I added a simple string replace for all underscores to simple slashes.

**PS**. This may be a problem with the main command `ddev config --auto` but since I could not touch the Go code there I made this small change here.

<a href="https://gitpod.io/#https://github.com/drud/ddev-gitpod-launcher/pull/13"></a>

### CODE REVIEW

**Review by rfay — APPROVED** [review]
Looks like it should be perfect. Also, we could use `ddev config --project-name=<fixedname>`

Got a repo you recommend trying it out on? I guess I have a couple, https://github.com/rfay/signing_tools etc.

**Comment by theodorosploumis** [comment]
I was trying to "ddevify' the https://github.com/goalgorilla/open_social to find out this issue.

**Review by rfay — CHANGES_REQUESTED** [review]
You seem to have pushed the wrong stuff in here now? You'll want to force-push the original change.

**Comment by theodorosploumis** [comment]
Let's close this PR totally. I need to create a clean PR.

**Comment by rfay** [comment]
All you had to do was to push (with a force) the already-approved change.

**Comment by rfay** [comment]
I see, you were using just the theodorosploumis/main branch and got it messed up with another PR. Make a new branch for every PR and things will come out better.

But all you have to do here is push https://github.com/drud/ddev-gitpod-launcher/pull/13/commits/0a25948696e13525e3628d0dc81ce51f80980f31 into theodorosploumis/main after rebasing to upstream/main. And if you want to make a different PR, make it with a new git branch.

**Pull request closed without merging**
